[versions]
kotlin = "2.1.20"
kotlinx-datetime = "0.6.1"
kotlinx-serialization-json = "1.7.3"
kotlinx-coroutines = "1.9.0"
auxframework = "75a2259840"
fuzzy-wuzzy = "1.4.0"

[libraries]
fuzzy-search = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzy-wuzzy" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
auxframework-application = { module = "com.github.StarryDevs.auxframework:aux-application", version.ref = "auxframework" }

[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization-json", "kotlinx-coroutines"]

[plugins]
node = { id = "com.github.node-gradle.node", version = "7.1.0" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-rc1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
