name: Build

on:
  push:
    branches: ['main']
    paths: ['src/**', 'src-vue/**', '**/*.gradle', 'gradle.properties']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew shadowJar

      - uses: actions/upload-artifact@v4
        with:
          name: meme-browser
          path: build/libs/
